name: MESSENGERuvvs

channels:
    - defaults

dependencies:
    - python>=3.6
    - astropy
    - numpy
    - bokeh
    - pip:
      - sphinx
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - sphinx-astropy
      - periodictable
